export const words = [
  "Scalable",
  "Cinephile",
  "COPY CAT",
  "Problem-solver",
  "Driven",
  "Introvert",
  "User-focused",
  "Leadership",
  "Big Eater",
  "Dynamic",
  "Self-Learner",
  "Creative",
  "Early Riser",
  "Design",
  "Health freak",
  "Full-Stack",
  "Swimmer",
  "Focused",
  "Listener",
  "COOK",
  "Resourceful",
  "Audiophile",
  "Innovative",
  "Ice Cream",
  "Analytical",
  "Collaborative",
  "Versatile",
  "Passionate",
  "Visualisation",
  "Adaptable",
];
